'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5466
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("e45d8263-3d3d-4391-ac52-9dae635b1552"),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("DB_momModel", "FK_hadir_non_pekerja", "non_pekerja", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(DB_momModel.non_pekerja), "hadir", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DB_momModel.hadir)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("DB_momModel", "FK_hadir_pekerja", "pekerja", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(DB_momModel.pekerja), "hadir", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DB_momModel.hadir))> 

'Original file name:
'Generation date: 2/18/2013 10:27:45 AM
Namespace DB_momModel
    '''<summary>
    '''There are no comments for DB_momEntities in the schema.
    '''</summary>
    Partial Public Class DB_momEntities
        Inherits Global.System.Data.Objects.ObjectContext
        '''<summary>
        '''Initializes a new DB_momEntities object using the connection string found in the 'DB_momEntities' section of the application configuration file.
        '''</summary>
        Public Sub New()
            MyBase.New("name=DB_momEntities", "DB_momEntities")
            Me.OnContextCreated
        End Sub
        '''<summary>
        '''Initialize a new DB_momEntities object.
        '''</summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "DB_momEntities")
            Me.OnContextCreated
        End Sub
        '''<summary>
        '''Initialize a new DB_momEntities object.
        '''</summary>
        Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
            MyBase.New(connection, "DB_momEntities")
            Me.OnContextCreated
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
        '''<summary>
        '''There are no comments for hadir in the schema.
        '''</summary>
        Public ReadOnly Property hadir() As Global.System.Data.Objects.ObjectQuery(Of hadir)
            Get
                If (Me._hadir Is Nothing) Then
                    Me._hadir = MyBase.CreateQuery(Of hadir)("[hadir]")
                End If
                Return Me._hadir
            End Get
        End Property
        Private _hadir As Global.System.Data.Objects.ObjectQuery(Of hadir)
        '''<summary>
        '''There are no comments for non_pekerja in the schema.
        '''</summary>
        Public ReadOnly Property non_pekerja() As Global.System.Data.Objects.ObjectQuery(Of non_pekerja)
            Get
                If (Me._non_pekerja Is Nothing) Then
                    Me._non_pekerja = MyBase.CreateQuery(Of non_pekerja)("[non_pekerja]")
                End If
                Return Me._non_pekerja
            End Get
        End Property
        Private _non_pekerja As Global.System.Data.Objects.ObjectQuery(Of non_pekerja)
        '''<summary>
        '''There are no comments for pekerja in the schema.
        '''</summary>
        Public ReadOnly Property pekerja() As Global.System.Data.Objects.ObjectQuery(Of pekerja)
            Get
                If (Me._pekerja Is Nothing) Then
                    Me._pekerja = MyBase.CreateQuery(Of pekerja)("[pekerja]")
                End If
                Return Me._pekerja
            End Get
        End Property
        Private _pekerja As Global.System.Data.Objects.ObjectQuery(Of pekerja)
        '''<summary>
        '''There are no comments for rapat in the schema.
        '''</summary>
        Public ReadOnly Property rapat() As Global.System.Data.Objects.ObjectQuery(Of rapat)
            Get
                If (Me._rapat Is Nothing) Then
                    Me._rapat = MyBase.CreateQuery(Of rapat)("[rapat]")
                End If
                Return Me._rapat
            End Get
        End Property
        Private _rapat As Global.System.Data.Objects.ObjectQuery(Of rapat)
        '''<summary>
        '''There are no comments for ruangan in the schema.
        '''</summary>
        Public ReadOnly Property ruangan() As Global.System.Data.Objects.ObjectQuery(Of ruangan)
            Get
                If (Me._ruangan Is Nothing) Then
                    Me._ruangan = MyBase.CreateQuery(Of ruangan)("[ruangan]")
                End If
                Return Me._ruangan
            End Get
        End Property
        Private _ruangan As Global.System.Data.Objects.ObjectQuery(Of ruangan)
        '''<summary>
        '''There are no comments for sysdiagrams in the schema.
        '''</summary>
        Public ReadOnly Property sysdiagrams() As Global.System.Data.Objects.ObjectQuery(Of sysdiagrams)
            Get
                If (Me._sysdiagrams Is Nothing) Then
                    Me._sysdiagrams = MyBase.CreateQuery(Of sysdiagrams)("[sysdiagrams]")
                End If
                Return Me._sysdiagrams
            End Get
        End Property
        Private _sysdiagrams As Global.System.Data.Objects.ObjectQuery(Of sysdiagrams)
        '''<summary>
        '''There are no comments for hadir in the schema.
        '''</summary>
        Public Sub AddTohadir(ByVal hadir As hadir)
            MyBase.AddObject("hadir", hadir)
        End Sub
        '''<summary>
        '''There are no comments for non_pekerja in the schema.
        '''</summary>
        Public Sub AddTonon_pekerja(ByVal non_pekerja As non_pekerja)
            MyBase.AddObject("non_pekerja", non_pekerja)
        End Sub
        '''<summary>
        '''There are no comments for pekerja in the schema.
        '''</summary>
        Public Sub AddTopekerja(ByVal pekerja As pekerja)
            MyBase.AddObject("pekerja", pekerja)
        End Sub
        '''<summary>
        '''There are no comments for rapat in the schema.
        '''</summary>
        Public Sub AddTorapat(ByVal rapat As rapat)
            MyBase.AddObject("rapat", rapat)
        End Sub
        '''<summary>
        '''There are no comments for ruangan in the schema.
        '''</summary>
        Public Sub AddToruangan(ByVal ruangan As ruangan)
            MyBase.AddObject("ruangan", ruangan)
        End Sub
        '''<summary>
        '''There are no comments for sysdiagrams in the schema.
        '''</summary>
        Public Sub AddTosysdiagrams(ByVal sysdiagrams As sysdiagrams)
            MyBase.AddObject("sysdiagrams", sysdiagrams)
        End Sub
    End Class
    '''<summary>
    '''There are no comments for DB_momModel.hadir in the schema.
    '''</summary>
    '''<KeyProperties>
    '''id_hadir
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="DB_momModel", Name:="hadir"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Serializable()>  _
    Partial Public Class hadir
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new hadir object.
        '''</summary>
        '''<param name="no_rapat">Initial value of no_rapat.</param>
        '''<param name="id_hadir">Initial value of id_hadir.</param>
        '''<param name="hadir1">Initial value of hadir1.</param>
        Public Shared Function Createhadir(ByVal no_rapat As Integer, ByVal id_hadir As Integer, ByVal hadir1 As String) As hadir
            Dim hadir As hadir = New hadir
            hadir.no_rapat = no_rapat
            hadir.id_hadir = id_hadir
            hadir.hadir1 = hadir1
            Return hadir
        End Function
        '''<summary>
        '''There are no comments for Property no_rapat in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property no_rapat() As Integer
            Get
                Return Me._no_rapat
            End Get
            Set
                Me.Onno_rapatChanging(value)
                Me.ReportPropertyChanging("no_rapat")
                Me._no_rapat = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("no_rapat")
                Me.Onno_rapatChanged
            End Set
        End Property
        Private _no_rapat As Integer
        Partial Private Sub Onno_rapatChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub Onno_rapatChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property id_hadir in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id_hadir() As Integer
            Get
                Return Me._id_hadir
            End Get
            Set
                Me.Onid_hadirChanging(value)
                Me.ReportPropertyChanging("id_hadir")
                Me._id_hadir = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("id_hadir")
                Me.Onid_hadirChanged
            End Set
        End Property
        Private _id_hadir As Integer
        Partial Private Sub Onid_hadirChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub Onid_hadirChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property hadir1 in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property hadir1() As String
            Get
                Return Me._hadir1
            End Get
            Set
                Me.Onhadir1Changing(value)
                Me.ReportPropertyChanging("hadir1")
                Me._hadir1 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
                Me.ReportPropertyChanged("hadir1")
                Me.Onhadir1Changed
            End Set
        End Property
        Private _hadir1 As String
        Partial Private Sub Onhadir1Changing(ByVal value As String)
        End Sub
        Partial Private Sub Onhadir1Changed()
        End Sub
        '''<summary>
        '''There are no comments for non_pekerja in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DB_momModel", "FK_hadir_non_pekerja", "non_pekerja"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property non_pekerja() As non_pekerja
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of non_pekerja)("DB_momModel.FK_hadir_non_pekerja", "non_pekerja").Value
            End Get
            Set
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of non_pekerja)("DB_momModel.FK_hadir_non_pekerja", "non_pekerja").Value = value
            End Set
        End Property
        '''<summary>
        '''There are no comments for non_pekerja in the schema.
        '''</summary>
        <Global.System.ComponentModel.BrowsableAttribute(false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property non_pekerjaReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of non_pekerja)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of non_pekerja)("DB_momModel.FK_hadir_non_pekerja", "non_pekerja")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of non_pekerja)("DB_momModel.FK_hadir_non_pekerja", "non_pekerja", value)
                End If
            End Set
        End Property
        '''<summary>
        '''There are no comments for pekerja in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DB_momModel", "FK_hadir_pekerja", "pekerja"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property pekerja() As pekerja
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of pekerja)("DB_momModel.FK_hadir_pekerja", "pekerja").Value
            End Get
            Set
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of pekerja)("DB_momModel.FK_hadir_pekerja", "pekerja").Value = value
            End Set
        End Property
        '''<summary>
        '''There are no comments for pekerja in the schema.
        '''</summary>
        <Global.System.ComponentModel.BrowsableAttribute(false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property pekerjaReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of pekerja)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of pekerja)("DB_momModel.FK_hadir_pekerja", "pekerja")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of pekerja)("DB_momModel.FK_hadir_pekerja", "pekerja", value)
                End If
            End Set
        End Property
    End Class
    '''<summary>
    '''There are no comments for DB_momModel.non_pekerja in the schema.
    '''</summary>
    '''<KeyProperties>
    '''id_non_pekerja
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="DB_momModel", Name:="non_pekerja"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Serializable()>  _
    Partial Public Class non_pekerja
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new non_pekerja object.
        '''</summary>
        '''<param name="id_non_pekerja">Initial value of id_non_pekerja.</param>
        '''<param name="nama">Initial value of nama.</param>
        '''<param name="instansi">Initial value of instansi.</param>
        '''<param name="email_address">Initial value of email_address.</param>
        Public Shared Function Createnon_pekerja(ByVal id_non_pekerja As Integer, ByVal nama As String, ByVal instansi As String, ByVal email_address As String) As non_pekerja
            Dim non_pekerja As non_pekerja = New non_pekerja
            non_pekerja.id_non_pekerja = id_non_pekerja
            non_pekerja.nama = nama
            non_pekerja.instansi = instansi
            non_pekerja.email_address = email_address
            Return non_pekerja
        End Function
        '''<summary>
        '''There are no comments for Property id_non_pekerja in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id_non_pekerja() As Integer
            Get
                Return Me._id_non_pekerja
            End Get
            Set
                Me.Onid_non_pekerjaChanging(value)
                Me.ReportPropertyChanging("id_non_pekerja")
                Me._id_non_pekerja = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("id_non_pekerja")
                Me.Onid_non_pekerjaChanged
            End Set
        End Property
        Private _id_non_pekerja As Integer
        Partial Private Sub Onid_non_pekerjaChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub Onid_non_pekerjaChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property nama in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property nama() As String
            Get
                Return Me._nama
            End Get
            Set
                Me.OnnamaChanging(value)
                Me.ReportPropertyChanging("nama")
                Me._nama = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
                Me.ReportPropertyChanged("nama")
                Me.OnnamaChanged
            End Set
        End Property
        Private _nama As String
        Partial Private Sub OnnamaChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnnamaChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property instansi in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property instansi() As String
            Get
                Return Me._instansi
            End Get
            Set
                Me.OninstansiChanging(value)
                Me.ReportPropertyChanging("instansi")
                Me._instansi = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
                Me.ReportPropertyChanged("instansi")
                Me.OninstansiChanged
            End Set
        End Property
        Private _instansi As String
        Partial Private Sub OninstansiChanging(ByVal value As String)
        End Sub
        Partial Private Sub OninstansiChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property email_address in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property email_address() As String
            Get
                Return Me._email_address
            End Get
            Set
                Me.Onemail_addressChanging(value)
                Me.ReportPropertyChanging("email_address")
                Me._email_address = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
                Me.ReportPropertyChanged("email_address")
                Me.Onemail_addressChanged
            End Set
        End Property
        Private _email_address As String
        Partial Private Sub Onemail_addressChanging(ByVal value As String)
        End Sub
        Partial Private Sub Onemail_addressChanged()
        End Sub
        '''<summary>
        '''There are no comments for hadir in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DB_momModel", "FK_hadir_non_pekerja", "hadir"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property hadir() As Global.System.Data.Objects.DataClasses.EntityCollection(Of hadir)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of hadir)("DB_momModel.FK_hadir_non_pekerja", "hadir")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of hadir)("DB_momModel.FK_hadir_non_pekerja", "hadir", value)
                End If
            End Set
        End Property
    End Class
    '''<summary>
    '''There are no comments for DB_momModel.pekerja in the schema.
    '''</summary>
    '''<KeyProperties>
    '''nopek
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="DB_momModel", Name:="pekerja"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Serializable()>  _
    Partial Public Class pekerja
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new pekerja object.
        '''</summary>
        '''<param name="nopek">Initial value of nopek.</param>
        '''<param name="nama_pekerja">Initial value of nama_pekerja.</param>
        '''<param name="jabatan">Initial value of jabatan.</param>
        '''<param name="email_address">Initial value of email_address.</param>
        Public Shared Function Createpekerja(ByVal nopek As String, ByVal nama_pekerja As String, ByVal jabatan As String, ByVal email_address As String) As pekerja
            Dim pekerja As pekerja = New pekerja
            pekerja.nopek = nopek
            pekerja.nama_pekerja = nama_pekerja
            pekerja.jabatan = jabatan
            pekerja.email_address = email_address
            Return pekerja
        End Function
        '''<summary>
        '''There are no comments for Property nopek in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property nopek() As String
            Get
                Return Me._nopek
            End Get
            Set
                Me.OnnopekChanging(value)
                Me.ReportPropertyChanging("nopek")
                Me._nopek = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
                Me.ReportPropertyChanged("nopek")
                Me.OnnopekChanged
            End Set
        End Property
        Private _nopek As String
        Partial Private Sub OnnopekChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnnopekChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property nama_pekerja in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property nama_pekerja() As String
            Get
                Return Me._nama_pekerja
            End Get
            Set
                Me.Onnama_pekerjaChanging(value)
                Me.ReportPropertyChanging("nama_pekerja")
                Me._nama_pekerja = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
                Me.ReportPropertyChanged("nama_pekerja")
                Me.Onnama_pekerjaChanged
            End Set
        End Property
        Private _nama_pekerja As String
        Partial Private Sub Onnama_pekerjaChanging(ByVal value As String)
        End Sub
        Partial Private Sub Onnama_pekerjaChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property jabatan in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property jabatan() As String
            Get
                Return Me._jabatan
            End Get
            Set
                Me.OnjabatanChanging(value)
                Me.ReportPropertyChanging("jabatan")
                Me._jabatan = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
                Me.ReportPropertyChanged("jabatan")
                Me.OnjabatanChanged
            End Set
        End Property
        Private _jabatan As String
        Partial Private Sub OnjabatanChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnjabatanChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property email_address in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property email_address() As String
            Get
                Return Me._email_address
            End Get
            Set
                Me.Onemail_addressChanging(value)
                Me.ReportPropertyChanging("email_address")
                Me._email_address = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
                Me.ReportPropertyChanged("email_address")
                Me.Onemail_addressChanged
            End Set
        End Property
        Private _email_address As String
        Partial Private Sub Onemail_addressChanging(ByVal value As String)
        End Sub
        Partial Private Sub Onemail_addressChanged()
        End Sub
        '''<summary>
        '''There are no comments for hadir in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("DB_momModel", "FK_hadir_pekerja", "hadir"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property hadir() As Global.System.Data.Objects.DataClasses.EntityCollection(Of hadir)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of hadir)("DB_momModel.FK_hadir_pekerja", "hadir")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of hadir)("DB_momModel.FK_hadir_pekerja", "hadir", value)
                End If
            End Set
        End Property
    End Class
    '''<summary>
    '''There are no comments for DB_momModel.rapat in the schema.
    '''</summary>
    '''<KeyProperties>
    '''no_rapat
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="DB_momModel", Name:="rapat"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Serializable()>  _
    Partial Public Class rapat
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new rapat object.
        '''</summary>
        '''<param name="no_rapat">Initial value of no_rapat.</param>
        Public Shared Function Createrapat(ByVal no_rapat As Integer) As rapat
            Dim rapat As rapat = New rapat
            rapat.no_rapat = no_rapat
            Return rapat
        End Function
        '''<summary>
        '''There are no comments for Property no_rapat in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property no_rapat() As Integer
            Get
                Return Me._no_rapat
            End Get
            Set
                Me.Onno_rapatChanging(value)
                Me.ReportPropertyChanging("no_rapat")
                Me._no_rapat = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("no_rapat")
                Me.Onno_rapatChanged
            End Set
        End Property
        Private _no_rapat As Integer
        Partial Private Sub Onno_rapatChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub Onno_rapatChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property tanggal_rapat in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property tanggal_rapat() As String
            Get
                Return Me._tanggal_rapat
            End Get
            Set
                Me.Ontanggal_rapatChanging(value)
                Me.ReportPropertyChanging("tanggal_rapat")
                Me._tanggal_rapat = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("tanggal_rapat")
                Me.Ontanggal_rapatChanged
            End Set
        End Property
        Private _tanggal_rapat As String
        Partial Private Sub Ontanggal_rapatChanging(ByVal value As String)
        End Sub
        Partial Private Sub Ontanggal_rapatChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property perihal in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property perihal() As String
            Get
                Return Me._perihal
            End Get
            Set
                Me.OnperihalChanging(value)
                Me.ReportPropertyChanging("perihal")
                Me._perihal = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("perihal")
                Me.OnperihalChanged
            End Set
        End Property
        Private _perihal As String
        Partial Private Sub OnperihalChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnperihalChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property tindak_lanjut in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property tindak_lanjut() As String
            Get
                Return Me._tindak_lanjut
            End Get
            Set
                Me.Ontindak_lanjutChanging(value)
                Me.ReportPropertyChanging("tindak_lanjut")
                Me._tindak_lanjut = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("tindak_lanjut")
                Me.Ontindak_lanjutChanged
            End Set
        End Property
        Private _tindak_lanjut As String
        Partial Private Sub Ontindak_lanjutChanging(ByVal value As String)
        End Sub
        Partial Private Sub Ontindak_lanjutChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property PIC in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PIC() As String
            Get
                Return Me._PIC
            End Get
            Set
                Me.OnPICChanging(value)
                Me.ReportPropertyChanging("PIC")
                Me._PIC = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("PIC")
                Me.OnPICChanged
            End Set
        End Property
        Private _PIC As String
        Partial Private Sub OnPICChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnPICChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property pimpinan_rapat in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property pimpinan_rapat() As String
            Get
                Return Me._pimpinan_rapat
            End Get
            Set
                Me.Onpimpinan_rapatChanging(value)
                Me.ReportPropertyChanging("pimpinan_rapat")
                Me._pimpinan_rapat = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("pimpinan_rapat")
                Me.Onpimpinan_rapatChanged
            End Set
        End Property
        Private _pimpinan_rapat As String
        Partial Private Sub Onpimpinan_rapatChanging(ByVal value As String)
        End Sub
        Partial Private Sub Onpimpinan_rapatChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property notulis in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property notulis() As String
            Get
                Return Me._notulis
            End Get
            Set
                Me.OnnotulisChanging(value)
                Me.ReportPropertyChanging("notulis")
                Me._notulis = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("notulis")
                Me.OnnotulisChanged
            End Set
        End Property
        Private _notulis As String
        Partial Private Sub OnnotulisChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnnotulisChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property no_ruangan in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property no_ruangan() As String
            Get
                Return Me._no_ruangan
            End Get
            Set
                Me.Onno_ruanganChanging(value)
                Me.ReportPropertyChanging("no_ruangan")
                Me._no_ruangan = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("no_ruangan")
                Me.Onno_ruanganChanged
            End Set
        End Property
        Private _no_ruangan As String
        Partial Private Sub Onno_ruanganChanging(ByVal value As String)
        End Sub
        Partial Private Sub Onno_ruanganChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property FileName in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileName() As String
            Get
                Return Me._FileName
            End Get
            Set
                Me.OnFileNameChanging(value)
                Me.ReportPropertyChanging("FileName")
                Me._FileName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("FileName")
                Me.OnFileNameChanged
            End Set
        End Property
        Private _FileName As String
        Partial Private Sub OnFileNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnFileNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property FileType in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileType() As String
            Get
                Return Me._FileType
            End Get
            Set
                Me.OnFileTypeChanging(value)
                Me.ReportPropertyChanging("FileType")
                Me._FileType = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("FileType")
                Me.OnFileTypeChanged
            End Set
        End Property
        Private _FileType As String
        Partial Private Sub OnFileTypeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnFileTypeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property FileData in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileData() As Byte()
            Get
                Return Global.System.Data.Objects.DataClasses.StructuralObject.GetValidValue(Me._FileData)
            End Get
            Set
                Me.OnFileDataChanging(value)
                Me.ReportPropertyChanging("FileData")
                Me._FileData = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("FileData")
                Me.OnFileDataChanged
            End Set
        End Property
        Private _FileData() As Byte
        Partial Private Sub OnFileDataChanging(ByVal value() As Byte)
        End Sub
        Partial Private Sub OnFileDataChanged()
        End Sub
    End Class
    '''<summary>
    '''There are no comments for DB_momModel.ruangan in the schema.
    '''</summary>
    '''<KeyProperties>
    '''no_ruangan
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="DB_momModel", Name:="ruangan"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Serializable()>  _
    Partial Public Class ruangan
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new ruangan object.
        '''</summary>
        '''<param name="no_ruangan">Initial value of no_ruangan.</param>
        Public Shared Function Createruangan(ByVal no_ruangan As String) As ruangan
            Dim ruangan As ruangan = New ruangan
            ruangan.no_ruangan = no_ruangan
            Return ruangan
        End Function
        '''<summary>
        '''There are no comments for Property no_ruangan in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property no_ruangan() As String
            Get
                Return Me._no_ruangan
            End Get
            Set
                Me.Onno_ruanganChanging(value)
                Me.ReportPropertyChanging("no_ruangan")
                Me._no_ruangan = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
                Me.ReportPropertyChanged("no_ruangan")
                Me.Onno_ruanganChanged
            End Set
        End Property
        Private _no_ruangan As String
        Partial Private Sub Onno_ruanganChanging(ByVal value As String)
        End Sub
        Partial Private Sub Onno_ruanganChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property no_lantai in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property no_lantai() As Global.System.Nullable(Of Integer)
            Get
                Return Me._no_lantai
            End Get
            Set
                Me.Onno_lantaiChanging(value)
                Me.ReportPropertyChanging("no_lantai")
                Me._no_lantai = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("no_lantai")
                Me.Onno_lantaiChanged
            End Set
        End Property
        Private _no_lantai As Global.System.Nullable(Of Integer)
        Partial Private Sub Onno_lantaiChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub Onno_lantaiChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property lokasi in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property lokasi() As String
            Get
                Return Me._lokasi
            End Get
            Set
                Me.OnlokasiChanging(value)
                Me.ReportPropertyChanging("lokasi")
                Me._lokasi = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("lokasi")
                Me.OnlokasiChanged
            End Set
        End Property
        Private _lokasi As String
        Partial Private Sub OnlokasiChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnlokasiChanged()
        End Sub
    End Class
    '''<summary>
    '''There are no comments for DB_momModel.sysdiagrams in the schema.
    '''</summary>
    '''<KeyProperties>
    '''diagram_id
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="DB_momModel", Name:="sysdiagrams"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Serializable()>  _
    Partial Public Class sysdiagrams
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new sysdiagrams object.
        '''</summary>
        '''<param name="name">Initial value of name.</param>
        '''<param name="principal_id">Initial value of principal_id.</param>
        '''<param name="diagram_id">Initial value of diagram_id.</param>
        Public Shared Function Createsysdiagrams(ByVal name As String, ByVal principal_id As Integer, ByVal diagram_id As Integer) As sysdiagrams
            Dim sysdiagrams As sysdiagrams = New sysdiagrams
            sysdiagrams.name = name
            sysdiagrams.principal_id = principal_id
            sysdiagrams.diagram_id = diagram_id
            Return sysdiagrams
        End Function
        '''<summary>
        '''There are no comments for Property name in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property name() As String
            Get
                Return Me._name
            End Get
            Set
                Me.OnnameChanging(value)
                Me.ReportPropertyChanging("name")
                Me._name = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
                Me.ReportPropertyChanged("name")
                Me.OnnameChanged
            End Set
        End Property
        Private _name As String
        Partial Private Sub OnnameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnnameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property principal_id in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property principal_id() As Integer
            Get
                Return Me._principal_id
            End Get
            Set
                Me.Onprincipal_idChanging(value)
                Me.ReportPropertyChanging("principal_id")
                Me._principal_id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("principal_id")
                Me.Onprincipal_idChanged
            End Set
        End Property
        Private _principal_id As Integer
        Partial Private Sub Onprincipal_idChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub Onprincipal_idChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property diagram_id in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property diagram_id() As Integer
            Get
                Return Me._diagram_id
            End Get
            Set
                Me.Ondiagram_idChanging(value)
                Me.ReportPropertyChanging("diagram_id")
                Me._diagram_id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("diagram_id")
                Me.Ondiagram_idChanged
            End Set
        End Property
        Private _diagram_id As Integer
        Partial Private Sub Ondiagram_idChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub Ondiagram_idChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property version in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property version() As Global.System.Nullable(Of Integer)
            Get
                Return Me._version
            End Get
            Set
                Me.OnversionChanging(value)
                Me.ReportPropertyChanging("version")
                Me._version = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("version")
                Me.OnversionChanged
            End Set
        End Property
        Private _version As Global.System.Nullable(Of Integer)
        Partial Private Sub OnversionChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnversionChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property definition in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property definition() As Byte()
            Get
                Return Global.System.Data.Objects.DataClasses.StructuralObject.GetValidValue(Me._definition)
            End Get
            Set
                Me.OndefinitionChanging(value)
                Me.ReportPropertyChanging("definition")
                Me._definition = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("definition")
                Me.OndefinitionChanged
            End Set
        End Property
        Private _definition() As Byte
        Partial Private Sub OndefinitionChanging(ByVal value() As Byte)
        End Sub
        Partial Private Sub OndefinitionChanged()
        End Sub
    End Class
End Namespace
